name: easychat
description: "Full featured and complete chat package for Flutter and Firebase"
version: 0.0.5
homepage: https://github.com/thruthesky/easychat

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  easyuser: ^0.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
